### PR TITLE
[AST-12] Fix text input error layout

### PR DESCRIPTION
**Pull request by julianosbento**
# What
- Fix `TextInput`

# Why
- Fix problems raised after components implemented at `mobile-app`

# How
- Fix `TextInput` erro message layout
- Add `hasError` and `hasFocus` to `InputEyeToggle` component
- Fix `TextInput` behavior when is `password` field

[AST-12](https://produtomagnetis.atlassian.net/browse/AST-12)

### CODE REVIEW

**Review by carlosberti — DISMISSED** [review]
LGTM!

**Review by pedro-cerdera — DISMISSED** [review]

**Review by murillo94 — APPROVED** [review]

**Comment by murillo94** [comment]
Acho que faltou testar o uso de `getInputBorderColor` no arquivo `src/components/Inputs/InputEyeToggle.tsx`, não?

**Review by carlosberti — DISMISSED** [review]

**Review by LopesAlysson — APPROVED** [review]

**Review by LopesAlysson — CHANGES_REQUESTED** [review]
This commit message doesn't tell the changes that have been made.

**Review by LopesAlysson — APPROVED** [review]

**Comment by julianosbento** [comment]
> Acho que faltou testar o uso de `getInputBorderColor` no arquivo `src/components/Inputs/InputEyeToggle.tsx`, não?

Comments here, are in English, and about this point, we didn't tested that, because the `react-native-svg` don't gives support, for color property, and the icon, don't recognize the hexadecimal.

I aligned this missing test previously with @LopesAlysson!

**Pull request merged**
