### PR TITLE
fix(TextInput): fix input text label animation

### PR DESCRIPTION
**Pull request by renatofreire**
# What

Fix text input label animation

# Why

When a input starts with value, the label doesn't animate correctly

# How

Considering the value in animation rule

### CODE REVIEW

**Review by pedro-cerdera — APPROVED** [review]

**Review by victorheringer — APPROVED** [review]
LGTM

**Review by LopesAlysson — APPROVED** [review]
:shipit:

**Review by LopesAlysson — CHANGES_REQUESTED** [review]
I think it's important to implement a test case for this scenario

**Review by LopesAlysson — APPROVED** [review]
:shipit:

**Review by LopesAlysson — APPROVED** [review]

**Pull request merged**
